"""PostgreSQL persistence layer for the fitness assistant.

All database I/O is isolated here.  The rest of the application imports
only the public functions — no raw psycopg2 calls outside this module.

Environment variables (with defaults for local docker-compose):
    POSTGRES_HOST     – default: "postgres"
    POSTGRES_DB       – default: "fitness_assistant"
    POSTGRES_USER     – default: "user"
    POSTGRES_PASSWORD – default: "password"
    TZ                – default: "Europe/Berlin"
"""

import os
from contextlib import contextmanager
from datetime import datetime
from zoneinfo import ZoneInfo

import psycopg2
from psycopg2.extras import DictCursor

_TZ = ZoneInfo(os.getenv("TZ", "Europe/Berlin"))


# ---------------------------------------------------------------------------
# Connection management
# ---------------------------------------------------------------------------

def _get_db_connection() -> psycopg2.extensions.connection:
    """Open and return a new database connection."""
    return psycopg2.connect(
        host=os.getenv("POSTGRES_HOST", "postgres"),
        database=os.getenv("POSTGRES_DB", "fitness_assistant"),
        user=os.getenv("POSTGRES_USER", "user"),
        password=os.getenv("POSTGRES_PASSWORD", "password"),
    )


@contextmanager
def _db_cursor():
    """Context manager: yields a DictCursor and commits on clean exit."""
    conn = _get_db_connection()
    try:
        with conn.cursor(cursor_factory=DictCursor) as cur:
            yield cur
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


# ---------------------------------------------------------------------------
# Schema management
# ---------------------------------------------------------------------------

_CREATE_CONVERSATIONS = """
CREATE TABLE IF NOT EXISTS conversations (
    id                   TEXT PRIMARY KEY,
    question             TEXT NOT NULL,
    answer               TEXT NOT NULL,
    model_used           TEXT NOT NULL,
    response_time        FLOAT NOT NULL,
    relevance            TEXT NOT NULL,
    relevance_explanation TEXT NOT NULL,
    prompt_tokens        INTEGER NOT NULL,
    completion_tokens    INTEGER NOT NULL,
    total_tokens         INTEGER NOT NULL,
    eval_prompt_tokens   INTEGER NOT NULL,
    eval_completion_tokens INTEGER NOT NULL,
    eval_total_tokens    INTEGER NOT NULL,
    groq_cost            FLOAT NOT NULL,
    timestamp            TIMESTAMP WITH TIME ZONE NOT NULL
)
"""

_CREATE_FEEDBACK = """
CREATE TABLE IF NOT EXISTS feedback (
    id                SERIAL PRIMARY KEY,
    conversation_id   TEXT REFERENCES conversations(id),
    feedback          INTEGER NOT NULL,
    timestamp         TIMESTAMP WITH TIME ZONE NOT NULL
)
"""


def init_db() -> None:
    """Create the database schema (idempotent — safe to run multiple times).

    Uses ``CREATE TABLE IF NOT EXISTS`` so existing data is preserved.
    Call this once on first start, or include it in your container
    entrypoint / health-check initialisation logic.
    """
    with _db_cursor() as cur:
        cur.execute(_CREATE_CONVERSATIONS)
        cur.execute(_CREATE_FEEDBACK)
    print("Database schema initialised.")


# ---------------------------------------------------------------------------
# Write operations
# ---------------------------------------------------------------------------

def save_conversation(
    conversation_id: str,
    question: str,
    answer_data: dict,
    timestamp: datetime | None = None,
) -> None:
    """Persist a completed RAG conversation to the database.

    Args:
        conversation_id: UUID string generated by the API.
        question: The original user question.
        answer_data: The complete dict returned by ``rag.pipeline.rag()``.
        timestamp: Override the recorded time (defaults to now in local TZ).
    """
    if timestamp is None:
        timestamp = datetime.now(_TZ)

    with _db_cursor() as cur:
        cur.execute(
            """
            INSERT INTO conversations (
                id, question, answer, model_used, response_time,
                relevance, relevance_explanation,
                prompt_tokens, completion_tokens, total_tokens,
                eval_prompt_tokens, eval_completion_tokens, eval_total_tokens,
                groq_cost, timestamp
            ) VALUES (
                %s, %s, %s, %s, %s,
                %s, %s,
                %s, %s, %s,
                %s, %s, %s,
                %s, %s
            )
            ON CONFLICT (id) DO NOTHING
            """,
            (
                conversation_id,
                question,
                answer_data["answer"],
                answer_data["model_used"],
                answer_data["response_time"],
                answer_data["relevance"],
                answer_data["relevance_explanation"],
                answer_data["prompt_tokens"],
                answer_data["completion_tokens"],
                answer_data["total_tokens"],
                answer_data["eval_prompt_tokens"],
                answer_data["eval_completion_tokens"],
                answer_data["eval_total_tokens"],
                answer_data["groq_cost"],
                timestamp,
            ),
        )


def save_feedback(
    conversation_id: str,
    feedback: int,
    timestamp: datetime | None = None,
) -> None:
    """Record a thumbs-up (+1) or thumbs-down (-1) for a conversation.

    Args:
        conversation_id: Must reference an existing conversation row.
        feedback: +1 (positive) or -1 (negative).
        timestamp: Override the recorded time (defaults to now in local TZ).
    """
    if timestamp is None:
        timestamp = datetime.now(_TZ)

    with _db_cursor() as cur:
        cur.execute(
            "INSERT INTO feedback (conversation_id, feedback, timestamp) VALUES (%s, %s, %s)",
            (conversation_id, feedback, timestamp),
        )
